server:
  port: 8081
  servlet:
    #context path /api no need to add in spring config file with HttpSecurity class otherwise permitAll() also wil sk credentials
    context-path: /api

spring:
  application:
    name: API-GATEWAY-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/spring
    username: root
    password: mysql
  jpa:
    show-sql: false
#    hibernate:
#      ddl-auto: update
# To configure user details credentials
#  security:
#    user:
#      name: mk
#      password: mk